assets/js/analyzer.js, assets/js/generator.js, assets/js/sandbox.js, assets/js/translator.js
This code will prevent two translation requests from happening at the same time.
from task comment I made:
There are two ways I can think of handling this. One is that we should abort any request irrespective of what it is doing when a new request is asked for, this is a simple method. Another is much more complicated. We maintain context of which side (src or dst) changed. Then we allow only one request per side at a time. As simple as this may sound the code becomes pretty complicated. What do you think? I am submitting the simpler approach. Not sure if it has bugs, but as far as I have tested it doesn't seem to have any weird bugs and since I have a 10kBps connection the requests are slow and it's much easier to test :smile:
=> Maintain order of interactions

assets/js/persistence.js, assets/js/translator.js
Deprecation warning for `ev.totalSize` still persists, even though the warning for `ev.position` is gone, so I removed totalSize completely
=> Fix deprecation warnings for webkitURL and XMLHttpRequest event properties

assets/js/analyzer.js, assets/js/generator.js
This patch fixes the type error `undefined` that is displayed in the console when the user clicks on `Analyse` or `Generate` without selecting an item from the dropdown. This PR aims to solve issue #122 . 
Following are the screenshots:
**Before:** 
**After:**
The similar holds for Generate mode too.
=> TypeError fixed in analyse and generate modes

assets/js/translator.js
This patch first checks whether the data from `#originalText` is not empty. It lets the user make a `Detect Language` request only when the data is non-empty thereby, removing the `400-Bad Request Error.` This PR aims to solve the issue #124 . Following are the screenshots:
**Before**
**After**
=> Removes the 400-Bad request error when detect language is clicked

assets/css/style.css
Fixes issue #65 .
The fix ensures that there is no overlap between `swapButton` and the `srcLangSelectors` divs in any case.
=> Fixes the issue of dropdown button being overlapped

assets/js/util.js
Attempt to fix #149 . I add a `stop()` method to the `hide()` and `show()` methods on clicking a container nav option. This ensures that when a nav `mode` is clicked, all animations applied on the navbar modes stop and continue afresh. According to me, currently, as the animations are not queued up( as `queue: false` ), clicking on another `mode` whilst a transitional animation is going on kind of messes up with the animations. All the records of animations get vanished thereby resulting in a blank screen.
=> Fix container animation issue - issue 149

assets/js/translator.js
Fixes #170 . This PR selects a destination language for a selected source language for the views (-xs). This patch also implements the behaviour discussed in this [comment](https://github.com/goavki/apertium-html-tools/issues/170#issuecomment-317164866). - L199. If this behaviour is incorrect, we could simply remove this line.
=> Auto select of destination language for a source language on small screen - Fix #170

assets/js/translator.js
This PR aims to solve #166 . `translateText` now defers until `detectLanguage` is called. Also, `detectLanguage` is wrapped around `callApy()` method.
=> translateText() called only after detectLanguage() completes - fix issue #166

assets/js/translator.js
Fixes #131 . `autoDstSelectLang()` must be called corresponding to the `cursSrcLang` in the success handler of `detectLanguage()` to obtain the corresponding destination language. Irrespective of whether the `newDstLang` is present in the `recentDstLangs`, the `curDstLang` must be updated with the `newDstLang`.
=> autoDstSelectLang() called inside detectLanguage() and updates URL - Fix #131

assets/js/util.js
`handleAPyRequestCompletion()` called only if an AJAX request is invoked from within `callApy()` (As `apyRequestStartTime` is defined in this function). If any other AJAX request is made, as `aspRequestStartTime` would be undefined, the above check would not be made and thus, it will not show the installation Notification erroneously. Fix #190 .
=> apyRequestStartTime made null after every APy call - Fix #190

assets/js/translator.js
=> Use translateBtn class commonly across interface for 'translate' button - Fix #192

.htmlhintrc.json, assets/css/style.css, index.html.in
Eliminates inline styling from index.html.in
Adds HTML Lint rule "inline-style-disabled": true
Moves all inline styling code to assets/css/style.css
Related to Issue https://github.com/goavki/apertium-html-tools/issues/114
Done according to: https://codein.withgoogle.com/dashboard/task-instances/5437388455149568/
=> Removes inline styling

assets/js/translator.js
I added a non-breaking workaround for issue #97 in IE10 and 11.  
I tested both of them in virtual machine at Sauce Labs, logs for [IE10](https://saucelabs.com/beta/tests/5b3dda1b469941da93b32821ce818a62/metadata) and [IE11](https://saucelabs.com/beta/tests/f3bd41c0197b44cc9a02aabd83d5e30e/metadata).  
Also checked Chrome 62 locally and can confirm it works as before the change.
This is a part of [Google Code-In task](https://codein.withgoogle.com/dashboard/task-instances/5358971881783296/)
(Screenshot from IE)
=> File download in IE10+ fixing #97

assets/js/translator.js, assets/strings/arg.json, assets/strings/ava.json, assets/strings/cat.json, assets/strings/deu.json, assets/strings/eng.json, assets/strings/eus.json, assets/strings/fin.json, assets/strings/fra.json, assets/strings/heb.json, assets/strings/kaa.json, assets/strings/kaz.json, assets/strings/kir.json, assets/strings/nno.json, assets/strings/nob.json, assets/strings/oci.json, assets/strings/por.json, assets/strings/ron.json, assets/strings/rus.json, assets/strings/sme.json, assets/strings/spa.json, assets/strings/srd.json, assets/strings/swe.json, assets/strings/tat.json, assets/strings/tha.json, assets/strings/tur.json, assets/strings/uig.json, assets/strings/uzb.json, assets/strings/zho.json, index.html.in
I added another workaround to file downloading, this time for Safari. I tested it on Chrome 62 and Safari 9 (on cloud machine) but as it's not as clean workaround as #215 I'd recommend that someone with access to more local browsers would test this. The file now downloads and is correctly recognised but downloads without extension type and with name 'Unknown' but I can't find any better way to do that.
I also updated the English string to be more specific in current situation but I didn't want to break anything so I left other languages untouched.
[Logs for Safari 9](https://saucelabs.com/beta/tests/7c83ff01d5b348cb82612ae835ae0834)
This is a part of [GCI task](https://codein.withgoogle.com/dashboard/task-instances/5358971881783296/)
=> Add file download workaround for Safari (progress #97)

assets/js/translator.js
=> Context size fixed

assets/js/translator.js
Removes variant formatting for mobile because it doesn't show up anyways.
=> Removes variant format on mobile selection.

assets/js/localization.js, assets/js/translator.js
Fixes #333 
What was happening was that the available width was being calculated assuming that the source buttons were on the left and the target buttons were on the right, which is only the case if the language is ltr, so the code thought that there was much less space than there really was.
=> Fixed dropdowns in RTL mode

assets/js/localization.js, assets/js/persistence.js, assets/js/translator.js
more sensible default language pair when apertium.org is loaded. I think it might work!
=> More sensible default language pair

assets/js/.eslintrc.json, assets/js/analyzer.js, assets/js/generator.js, assets/js/init.js, assets/js/localization.js, assets/js/persistence.js, assets/js/sandbox.js, assets/js/translator.js, assets/js/util.js
The diff from https://github.com/apertium/apertium-html-tools/pull/400 has superfluous line changes, which made me realize this project enforces no trailing commas. So change that to enforce trailing commas, except for function args, as this reduces diff overhead and copy-paste errors. It is a travesty that JSON doesn't allow trailing commas, but we should absolutely require it for all JS lists.
=> Change ESLint comma-dangle to always-multiline, except for function args

build.ts
As per https://esbuild.github.io/api/#target default is `esnext` which is way too new. Target should be $YEAR - 5, currently ES2016.
=> Target ES2019 (fixes #417)

src/components/LocaleSelector.tsx, src/components/navbar/__tests__/index.test.tsx, src/components/navbar/index.tsx, src/components/navbar/navbar.css
Fixes https://github.com/apertium/apertium-html-tools/issues/451 and moves the collapse button to be horizontally aligned with the tagline rather than below it:
Before:
After:
=> Rewrite navbar layout

build.ts, package.json
fixes #477 
**Description :**
This pull request addresses the issue where the build process was relying on Git for version information. The problem arose when the build process did not have Git available.
**Changes Made :**
-In package.json, updated the `version` field to the latest released GitHub version
-In build.ts, modified the code to use the version specified in package.json.
=> fixes #477 (Build should not rely on git)

config.ts, src/components/footer/AboutModal.tsx, src/components/footer/__tests__/index.test.tsx, src/strings/eng.json, src/types.ts
**Description:**
This PR addresses issue #361 and also builds upon and supersedes the changes proposed in PR #422.
**Changes Made:**
- Modified `config.ts` by adding `showMoreLanguagesLink` and specified its type as `boolean` in `types.ts`. Also, added `more_languages` to `stringReplacements`.
- Modified `AboutModal.tsx` by conditionally rendering `more_languages` based on the value of `shouldDisplayString`, either true or false.
- In `index.test.tsx`, modified a test to check if, when the About dialog is opened and `showMoreLanguagesLink` is set to `true`, it should render the `more_languages`. Similarly, when `showMoreLanguagesLink` is set to `false` and the About dialog is opened, it should not render the `more_languages`.
=> added a string directing to beta.apertium.org

src/components/footer/__tests__/index.test.tsx, src/components/footer/index.tsx
#468 Issue
This pull request addresses an issue where the footer was not rendering on smaller screens due to the d-none class. The visibility of the footer is crucial for providing a seamless user experience across different devices.
- Removed the d-none class from the div in the footer folder index file, enabling the footer to be visible on smaller screens.
The d-none class was unintentionally hiding the footer on smaller screens, affecting the overall user experience. This change ensures consistent visibility across all screen sizes. The d-none class in Bootstrap is a utility class that sets an element to display: none! important;, effectively hiding it.
**before**
**After**
- Tested on various devices and screen sizes.
-  Ensured the removal of the d-none class did not introduce any …
=> Fix: Ensure Footer Visibility on Smaller Screens
