apertium/apertium-html-tools

assets/js/translator.js
index.html.in

Added the user interface only for website translation.

Added User interface for website translation.

---

assets/js/localization.js

Switch translation not available text instantly on changing language

---

Makefile
index.html.in

Tested everything with [jquery migrate](https://github.com/jquery/jquery-migrate/) as well, everything is working perfectly.

Update boostrap, jquery, font awesome and  bootstrap-rtl

---

assets/js/analyzer.js
assets/js/generator.js
assets/js/localization.js
assets/js/persistence.js
assets/js/translator.js

Fix #14
My internet has been acting up lately, sorry if I forgot something.
[Task](https://codein.withgoogle.com/dashboard/task-instances/6463955165773824/?sp-page=1)

Add 'q' parameter to URL

---

assets/js/localization.js

One line that ruined it for firefox. :100: 
Fixes #40 
PR 42!

Fix firefox rtl bug

---

assets/js/translator.js

Now the source textarea expands with content using whitespace below

Auto resize textareas

---

index.html.in

Html-tools: Subresource Integrity ([this issue](https://github.com/goavki/apertium-html-tools/issues/50)).

Html-tools: Subresource Integrity

---

assets/css/style.css
assets/js/translator.js
index.html.in
tools/read-conf.py

Add basic chained translation functionality.

---

assets/js/translator.js

Call translateDoc() only when the div is visible - Fix issue 161

---

assets/js/translator.js

Fix #168 . Irrespective of whether the `dstLang` is present in `recentSrcLangs`, the `select` values for `srcLangSelect` and `dstLangSelect` must be swapped.

Swap functionality for smaller screen - Fixes issue 168

---

assets/js/translator.js

Disable detectLang on translateDoc interface, enable otherwise

---

assets/js/analyzer.js
assets/js/generator.js

Fixes #172 . Checks if the input is non-empty. If empty, simply returns.

Check for the Analyzer input and return if the input is empty - Fix #172

---

index.html.in

Analyze and Generate buttons aligned

---

assets/js/sandbox.js

APy Sandbox request made on non-empty inputs only

---

assets/js/analyzer.js
assets/js/generator.js
assets/js/translator.js
assets/js/util.js

apyRequestTimeout cleared on request abort - Fix #185

---

assets/js/analyzer.js
assets/js/generator.js
assets/js/sandbox.js

Enter does not call analyze, generate, sanbox requests on empty input - Fix #188

---

assets/js/translator.js

translate() called when any of src or dst languages is changed - Fix #194

---

assets/css/style.css
assets/js/translator.js
assets/strings/eng.json
config.conf.example

Marks multi-step destinations with a '+' sign, explanation string added only for English. (Attempt to fix #120)

Mark multi-step destinations

---

.circleci/config.yml
.flowconfig
Makefile
assets/js/analyzer.js
assets/js/init.js
assets/js/translator.js
assets/js/util.js
debug-head.html
interfaces/config.js.flow

* Disentangle JS modules
* Fix imports
* Use flow on individual files
* Declare modules to Flow
* Run Flow directly
* Cleanup
* Fix some import/export issues

Disentangle JS modules (fixes #80)

---

assets/css/translation.css
assets/js/translator.js

Fix buggy UI with detect-language.

---

assets/js/translator.js

Fixes #241 
@sushain97 Friendly ping.

Use activeAfterCancel for 'Detect Language' consistently

---

assets/js/persistence.js
assets/js/sandbox.js
assets/strings/eng.json
flow-typed/jquery.js.flow
index.html.in

Fixes #147.
Also fixes `Uncaught TypeError: Cannot read property 'replace' of undefined` when loading sandbox.

Display APy endpoint in sandbox.

---

.circleci/config.yml
Makefile
README.md
docker/Dockerfile

Towards #130
#243 @sushain97 /cc

Compress HTML

---

index.html.in

Currently, the analyse and generate buttons are aligned incorrectly with the input text box in the morphological analysis and morphological generation tabs.
I have fixed this issue by adding one more class `col-md-offset-1` in both the divs in which the buttons are contained. Now, the buttons will remain perfectly aligned with the text box on any viewport.
refs #49

Fixed alignment issue of analyse and generate buttons

---

assets/js/analyzer.js
assets/js/translator.js
assets/js/util.js

Removed soft hyphens before translating/analyzing

---

assets/js/translator.js

Fixed extraneous instant translation

---

assets/css/translation.css
assets/js/localization.js
index.html.in

Displays translation options correctly in one line

---

html/index.html.in

cf. 4af78d57643803cb77e4a8318d70aec488fe0d18

hint to hit return

---

assets/js/translator.js

The swap button will now swap the texts of the textarea boxes.
Fixes: #376

Swap text with swap button

---

assets/js/translator.js

Reverts apertium/apertium-html-tools#396

Revert "Swap text with swap button"

---

Makefile

faster than waiting for CI over and over again

`make test` to run the stuff from CircleCI

---

src/index.html

noscript tag

---

.eslintrc.json
package.json
src/components/WithInstallationAlert.tsx
yarn.lock

- Upgrade testing deps
- Fix unmounted component state updates

upgrade testing deps

---

src/components/translator/DocTranslationForm.tsx
src/components/translator/Translator.tsx
src/components/translator/WebpageTranslationForm.tsx
src/components/translator/__tests__/DocTranslationForm.test.tsx
src/components/translator/__tests__/WebpageTranslationForm.test.tsx

https://github.com/apertium/apertium-html-tools/issues/439

Support pairprefs in doc and web translation

---

build.ts

Build improvements

---

src/components/translator/TranslationOptions.tsx

Hopefully fixes https://github.com/apertium/apertium-html-tools/issues/435 (sorry for the delay on this).
It isn't the _greatest_ but I think it's reasonable enough?

Tweak style prefs layout
